---
title: "rUMLS"
author: "Matthew Pancia"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
## Introduction 

rUMLS is an interface to the National Library of Medicine's [Unified Medicial Language System](https://www.nlm.nih.gov/research/umls/). The UMLS provides a way of linking many disparate medical vocabularies into a single graph, allowing for the unification of concepts and relations across these vocabularies. 

There are several ways of accessing the UMLS: 

* The [web interface](https://uts.nlm.nih.gov/home.html) provided by the NLM;
* The [REST API](https://documentation.uts.nlm.nih.gov/rest/home.html);
* The [SOAP API](https://documentation.uts.nlm.nih.gov/soap/home.html);
* A [download](https://www.nlm.nih.gov/research/umls/licensedcontent/downloads.html) of the underlying data, which allows for the creation of SQL load scripts.

The goal of this package is to provide an abstracted interface to the REST API provided by the NLM, making it easy to search for concepts, access relationships, and get other information like synonyms/translations/etc. Eventually, plotting tools and helper functions to understand the graphical structure will be added. 

## Authentication

This package requires a UMLS license, which includes user credentials. By using this package, you are subject to the licensing agreements that you agree to with the NLM. 

You can authenticate with the UMLS on a per-session basis using the `auth_UMLS()` function, but it is easier to include the relevant credentials in your `.Renviron` file located in your home directory. Add the following lines to your file:
```
UMLS_USER=<username>
UMLS_PASS=<password>
```

Once these are set, `auth_UMLS()` will load your credentials and authenticate you with the UMLS. If you wish to reset your credentials, use the `umls_creds()` function. 

## Structure of the UMLS

## Examples
